### 파이썬 리스트
: 가변형, 시퀸스 (str, list, tuple) = [+, *, 중첩, 슬라이싱, 인덱싱], []

### numpy = 수식 라이브러리, 수치연산, 배열객체
-- 동작 속도가 빠르다. / 연속적인 메모리 / 한가지 타입만 처리가능.


In [ ]:
np.array 로 객체생성
np.arange로 객체생성

In [3]:
# ndarray(shape[, dtype, buffer, offset, ...])
import numpy as np

In [121]:
a = np.array([0,1,2.0,3.0,4.0,5]) # => ndarray

In [122]:
print(a)
print(type(a))
print(a.dtype)

[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [12]:
a = np.array([0.0,1.0,3,4,5])
print(a)
print(type(a))
print(a.dtype) # a 객체가 가진 데이터 타입.  0,1 = bit *8 = 1byte = 주소가 생성

# 주소 생성 -> 메모리 할당, 값 대입
수형 short(2) ->int32(4) -> int64(8) -> long(8~16)dule
# 실수형 =floot(4) -> 'floot32', 'f4' -> fooly(8)  double(8)
# 문자와 문자열 -> str

#EX) int32 = 정수형 32=bit, 'i4' = 정수형 4byte
#    flooat64 = f8 = 실수형 64bit = 실수형 8byte


[0. 1. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [123]:
a = np.arange(10)
print(a)                #구분하기가 쉽지 않는다.        
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
####3) naaaray(shape[ , dtype, buffer, offset, ...]) / shape
3-1 : 차원 (Rank, Dimension)을 []로 갯수를 늘린다. [[[a]]] = 3차원, [[b]] = 2차원
    아벨 4차원이상 -> 컴
    
    대상 -> 특징추출(x_독립변수, y_종속변수) -> 도메인 -> 설명(통계_R) -> 예측(ML) 
    -> ML + AI = DL (CNN, 이미지 영상)
    
3-2 : 차원의 종류 
    1차원 : shape(x,)
    2차원 : shape(x,y), 행열(matrmix)
    3차원 : (x,y,z), (행,열,면) --> (면,행,열)
    n차원 : (x,y,z,,,,,,,)

In [22]:
#1차원 shape(x,)
a = np.arange(12)
print(a)
print(a.shape) # (12,) -> 1차원
t = a.shape
print(type(t))
print((a.shape)[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
<class 'tuple'>
12


In [24]:
# 2차원 배열의 Shape : 행(row, 수직(이미지연산),axis = 0)과 열(colimn, 수평(이미지연산), axis = 1)
m = np.array([[0,1,2],
              [0,1,2]])

print(m)
print(m.shape) #(2,3) --> 2차원, 행렬(matrix)
print(m.shape[0], m.shape[1])

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


4) 배열과 슬라이싱 _reshape()

In [144]:
# 2차원 배열 인덱싱 슬라이싱
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [30]:
# a 가진 값 0, 0, 9,를 리턴해보자 = 인덱싱
print(a[0][0])
print(a[0,0])
print(a[2][1])
print(a[2,3])

0
0
9
11


In [138]:
# a 가진 슬라이싱
print(a)
print("------------------")
print(a[0])
print(a[0, :]) #[행, 열]
print("------------------")
print(a[:,:-1]) # 마지막 열 제외
print(a[:,1:]) # 첫번째 열을 제외
print("------------------")
print('슬라이싱으로 전체 출력 형식을 만들자')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------
[0 1 2 3]
[0 1 2 3]
------------------
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
------------------
슬라이싱으로 전체 출력 형식을 만들자
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[0 1 2 3]]


In [34]:
# Q) 행의 모든 데이터를 20으로 변경 후 전체 출력 해보자.

In [36]:
a[0] = 20
print(a[:,:])
print(a[::2,::2]) #** p[start : end-1 : step]

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 20]
 [ 8 10]]


In [146]:
# 슬라이싱 요소 전체의 값을 변경해보자.
print(a[:,:])
print("-------------")
print(a[::2,::3])
print("-------------")
a[::2,::3] = 0
print(a[:,:])
print("-------------")
a[:,:] = -1
print(a[:,:])

[[ 0  1  2  0]
 [ 4  5  6  7]
 [ 0  9 10  0]]
-------------
[[0 0]
 [0 0]]
-------------
[[ 0  1  2  0]
 [ 4  5  6  7]
 [ 0  9 10  0]]
-------------
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [147]:
# 3차원 배열 인덱싱 슬라이싱
a = np.arange(12).reshape(2,2,3)
print(a,a.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [51]:
# 인덱싱
print(a[0][0][0])
print(a[0,0,0])
print(a[0,1,2]) # 5

0
0
5


In [156]:
# 슬라이싱
print(a[:,:,:]) # 전체출력
print("-------------")
print(a[:,1:,1:])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
-------------
[[[ 4  5]]

 [[10 11]]]


In [159]:
#[6,7]
#[4,5] 출력

#case 1 : 3차원
print(a[1:,:1,:2])
print(a[:-1,1:,1:])
print("-------------")

#case 2 : 1차원
print(a[1,0,:2])
print(a[0,1,1:])

[[[6 7]]]
[[[4 5]]]
-------------
[6 7]
[4 5]


5) 블린인덱싱 : 조건식을 이용한 인덱싱, 조건 검색 필터를 사용한 추출값 (중요!!)

In [107]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [87]:
print(a>2)
# 배열의 객체 a에서 2보다 큰 값을 배열로 리턴
print(a[a>2]) # -> 이미지 -> 빨간사과 -> 이상값(노이즈) 추출 해서 변경하고 싶다.

[False False  True  True  True  True]
[3 4 5 6]


In [108]:
bool_index = np.array([False, False, True, True, True, True])
print(a[bool_index])

[3 4 5 6]


In [100]:
#배열 a에서 3이 아닌 요소를 추출
#2보다 크고 6보다 작은 요소를 추출
#짝수만 추출
#평균보다 작은 값을 추출해보자.
a = np.array([1,2,3,4,5,6])
print(a[a!=3])
print(a[(a>2) & (a<6)])
print(a[a%2 == 0])
print(a[a< a.mean()], a.mean())

[1 2 4 5 6]
[3 4 5]
[2 4 6]
[1 2 3] 3.5


In [ ]:
# 6) 배열의 형상 다루기 : reshape(), flatten()(편평화),transpose()(전치) 

In [2]:
# flatten() : 다차원 배열을 1차원 배열로 만든다.
a = np.arange(12).reshape(3,4)
print(a,a.shape)

f = a.flatten()          # (3,4) ------> (12,)
print(f,f.shape)

NameError: name 'np' is not defined

In [118]:
# 데이터 순서를 거꾸로 변경
print(a[::-1])
print(a[:,::-1])
print(a[::-1,::-1])
print('-'*20)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
--------------------


In [162]:
# transpose() : 전치행렬, 행과 열을 서로 맞바꾸는 함수
t = a.transpose()
print(t,t.shape)      #(3,4) ----> (4,3)
print(a.T)            # transpose()함수와 동일한 결과

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [113]:
#### print(dir(a.T))
a.flat = 255
print(a)

[[255 255 255 255]
 [255 255 255 255]
 [255 255 255 255]]


In [4]:
d = np.arange(12).reshape(3,4)
print(d,d.shape)
print(d.dtype)  # int32 or int64
print(d.ndim)   # 2차원  ==> print(len(d.shape)) 와 동일
print(d.T)      # transpose()함수와 동일한 결과, 전치행렬
print(d.size)   # 12개 , 요소의 갯수
print(d.nbytes) # 48 bytes : 32bit(4 byte) * 12 
d.flat = 1
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
int64
2
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
12
96
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
#numpy 통계 함수들
a = np.arange(12).reshape(3,4)
print(a,a.shape)

print(a.max(),np.max(a))  #최대값
print(a.min(),np.min(a))  #최소값

print(a.sum())  # 합
print(a.mean())   # 평균

print(a.std())  #표준편차
print(a.var())  #분산
print(np.median(a))  #중위수

#사분위수
print('25%',np.percentile(a,25)) # 1사분위수(Q1)
print('50%',np.percentile(a,50)) # 2사분위수(Q2) median(a) 와 같은 값
print('75%',np.percentile(a,75)) # 3사분위수(Q3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
11 11
0 0
66
5.5
3.452052529534663
11.916666666666666
5.5
25% 2.75
50% 5.5
75% 8.25
